### PR TITLE
Merge in Faba-Mono

### LINKED ISSUE #36: Clean Git History
I'm gonna do a cleanup of the recent git history: of the 8 there, almost all of them seem to be doing things which get undone or redone almost immediately to the point where it's confusing to see what the changes made actually were.

### PR DESCRIPTION
**Pull request by Foggalong**
For reals this time; fixes #36. As mentioned there this relicenses the project to avoid conflicts, but also retains the modern icon file structure and drops the unused 22px size.

### CODE REVIEW

**Comment by fossfreedom** [comment]
appindicators default to 22px though.

**Comment by Foggalong** [comment]
@fossfreedom That's not good. Won't Faba not including 22px icons also cause a problem then?

**Comment by fossfreedom** [comment]
I've never seen any apps displayed in the appindicator using Faba icons - have seen just Moka icons in the app indicator ... and now Faba mono icons.

**Comment by Foggalong** [comment]
Oh wait, so *only* the app indicator is shown at 22px? What size does the rest of the panel default to?

**Comment by fossfreedom** [comment]
yep - only the app indicator.  Other panel icons size (I believe) between 16px and 24px depending upon the panel size.  App indicator icons don't resize

**Comment by Foggalong** [comment]
That's some... interesting behaviour. I'll bring in the 22px size too then :+1:

**Comment by fossfreedom** [comment]
its not clever.  almost defunct capability.  My understanding is that debian has an experimental project updating app indicators under a "ayatana" project - this removes cruft like this 22px non sizing stuff.

Also, budgie in a future release will likely bring in the more universal "status notifier" indicators  - again dont have this hard-coded 22px limit.

**Comment by Foggalong** [comment]
Ah okay, so it's more old cruft that's not been updated rather than a conscientious design decision. That makes more sense.

**Pull request merged**
