### PR TITLE
livepatch svg new

### PR DESCRIPTION
**Pull request by Gabb1995**

### CODE REVIEW

**Comment by Gabb1995** [comment]
I dont know if the icon can be more centralised so that the center of the "circle" is the same as the center of the box. If someone can do that so we can compare that would be nice :+1:

**Comment by fossfreedom** [comment]
That looks ideal.

Quick query though.  The .svg seems to have lost all of its layers. 

The updates need to be done on the icon layer otherwise the rendering script will not work.

Can you do this please?

**Comment by Gabb1995** [comment]
Not sure will take a look at it on Monday

**Comment by Gabb1995** [comment]
Should be fine now, let me know if not and I'll redo it!

**Pull request merged**
